name: Hello world!

on:
  push:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
    - name: fetch repository to runner
      uses: actions/checkout@v4  # Fetches the repo

    - name: versioning tracking
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: build docker image
      run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/java-hello-world:${{ github.run_number }}" --build-arg VERSION=${{ github.run_number }} .

    - name: log in to docker hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-hello-world:${{ github.run_number }}

