name: Hello world!

on:
  push:
    branches: ["master"]


# job configuration
jobs: 
  build-test:
    runs-on: ubuntu-latest # the github hosted runner
    
    steps:
    - name: fetch repository to runner
      uses: actions/checkout@v4 #this action is fetching my repository to my guthub runner

    - name: setup jdk 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: build with maven
      run: mvn -B package --file pom.xml

    - name: versioning tracking
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV 

    - name: Upload JAR file as an artifact
      uses: actions/upload-artifact@v4 #this action uploads the artifact (jar file) to github repository
      with:
        name: hello-world-${{ env.VERSION }}
        path: target/*.jar

