name: Hello world!

on:
  push:
    branches: ["master"]


# job configuration
jobs: 
  build-test:
    runs-on: ubuntu-latest # the github hosted runner
    
    steps:
    - name: fetch repository to runner
      uses: actions/checkout@v4 #this action is fetching my repository to my guthub runner

    - name: versioning tracking
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV 

    - name: build docker image
      run: docker build -t java-hello-world:{{ env.VERSION }} .

    - name: save image as artifact in github
      run: docker save -o java-hello-world-${{ env.VERSION }}.tar java-hello-world:${{ env.VERSION }}

    - name: save image as artifact in github
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-${{ env.VERSION }}
        path: java-hello-world-${{ env.VERSION }}.tar
