name: Hello world!

on:
  push:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
    - name: fetch repository to runner
      uses: actions/checkout@v4  # Fetches the repo

    - name: versioning tracking
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: build docker image
      run: docker build -t java-hello-world:${{ env.VERSION }} .

    - name: save docker image as tar file
      run: docker save -o java-hello-world-${{ env.VERSION }}.tar java-hello-world:${{ env.VERSION }}

    - name: save image as artifact in github
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-${{ env.VERSION }}
        path: java-hello-world-${{ env.VERSION }}.tar

